<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_link</name>
   <tag></tag>
   <elementGuidId>902dca07-bff5-4bb9-8181-858c5b671c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '#' and (text() = 'Edit' or . = 'Edit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbb6baf5-8c2a-4749-9e49-17e1e313a45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modifiers</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>4c9c5d9b-bda9-4793-8a75-7b02560deeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>edit_job</value>
      <webElementGuid>26a2b574-c1b7-4037-95e5-b23e4967e0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>7d8236cf-ee92-45c3-bab7-076b98b728ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1819b09f-f30f-4a3d-a446-64231694915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> oe_kanban_action oe_kanban_action_a</value>
      <webElementGuid>646bea8b-2520-4131-852b-9ca3a69630f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>f6eeef04-f5e5-4ab7-b930-e3d721e02f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_kanban_view oe_background_grey o_kanban_dashboard o_hr_recruitment_kanban ui-sortable o_kanban_grouped&quot;]/div[@class=&quot;o_kanban_group ui-sortable&quot;]/div[@class=&quot;oe_kanban_color_0 o_kanban_record o_dropdown_open&quot;]/div[@class=&quot;o_kanban_card_manage_pane dropdown-menu&quot;]/div[@class=&quot;o_kanban_card_manage_section&quot;]/div[3]/a[@class=&quot;oe_kanban_action oe_kanban_action_a&quot;]</value>
      <webElementGuid>18a8eade-f3b2-451e-9de1-c9473c7ec7eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[2]</value>
      <webElementGuid>00f733ec-3718-41c4-8cf8-d836848dd35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::a[3]</value>
      <webElementGuid>8a6030d5-c278-47a4-8960-0e173b5ec6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Description'])[1]/following::a[3]</value>
      <webElementGuid>1279446e-b1b6-4c32-823c-720c0e5bc375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new job 13:08:2023'])[1]/preceding::a[14]</value>
      <webElementGuid>20b7553a-11b3-4d0b-bf08-7616c361cf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>87d27440-43b9-4c25-bdae-7604b3a0771b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[36]</value>
      <webElementGuid>5ba17149-833d-477f-b249-481eb1499e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a</value>
      <webElementGuid>a2bef0d9-2ad5-4258-88cf-66aae1517e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>8e65edf2-bfda-41fb-b9a7-6db48794a121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
