<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu_link</name>
   <tag></tag>
   <elementGuidId>1d93de2b-d21b-462f-befa-2e76579b2dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.o_kanban_manage_toggle_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>734d1448-b1f6-43c4-b675-abb03016265c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_kanban_manage_toggle_button</value>
      <webElementGuid>2d1a5f58-e2f6-4143-929b-f2f6c191bd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a324e415-4c57-4b12-a164-bd5c44e02746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modifiers</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>e1e8e48a-4e0e-475d-abc2-76ef6c067c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_kanban_view oe_background_grey o_kanban_dashboard o_hr_recruitment_kanban ui-sortable o_kanban_grouped&quot;]/div[@class=&quot;o_kanban_group ui-sortable&quot;]/div[@class=&quot;oe_kanban_color_0 o_kanban_record o_dropdown_open&quot;]/div[@class=&quot;o_kanban_card_header&quot;]/div[@class=&quot;o_kanban_manage_button_section oe_kanban_color_0&quot;]/a[@class=&quot;o_kanban_manage_toggle_button&quot;]</value>
      <webElementGuid>951855bd-247a-4a65-a124-2b5da36c4027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit new DH job 13:08:2023'])[1]/following::a[2]</value>
      <webElementGuid>3293f5dd-6675-458b-9585-b72d3037f705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Requirements'])[1]/following::a[8]</value>
      <webElementGuid>4f38c14f-9011-407b-aac9-c7beee5f855a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[34]</value>
      <webElementGuid>3d3f371b-1406-4ee8-881e-472fc2826bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>4d21f262-9d89-4d53-846f-ca148b296d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>a8579bc1-2dac-4d29-9731-578be42adb14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
