<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invoice_Date_filed</name>
   <tag></tag>
   <elementGuidId>70b08ae8-396c-4c2f-9ec9-9c795442084f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_1932</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42b0d288-4032-47c3-ab65-b6e22f2d9b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d931b88e-ee09-4c06-83af-a12ce59ac0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_datepicker_input o_input datetimepicker-input</value>
      <webElementGuid>be6d45ea-15a7-4073-9fbe-09ce46bf0cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_date</value>
      <webElementGuid>82ff2e84-943b-4699-a2d1-53f98de4f83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#datepicker1966</value>
      <webElementGuid>ae9b029f-0aa6-4928-a8ba-6e267d5c00a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06469166-9149-456b-a3cf-6ff1c9884a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_1932</value>
      <webElementGuid>437fcbb3-2906-4e83-be77-e3095e03e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_1932&quot;)</value>
      <webElementGuid>6a36da20-daf7-4605-8bce-922a2937564a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_1932']</value>
      <webElementGuid>f38cef32-766f-47ac-a9c2-25f2dca6c70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker1966']/input</value>
      <webElementGuid>da87f0b2-c561-40e1-9464-a759087690e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>680a7af6-d4ee-424c-b3b9-ef809baca17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'invoice_date' and @id = 'o_field_input_1932']</value>
      <webElementGuid>3905db2b-9d83-4e63-9235-38827fd7599f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
