<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Description input</name>
   <tag></tag>
   <elementGuidId>858683be-0c35-417d-b457-c52a3e8d0bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_803</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>db9825c4-1b3c-40cd-bc31-dc7994ecdc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_text o_field_widget o_input</value>
      <webElementGuid>61cbc099-7e06-4a9e-899f-2b0a45628f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>fdb70216-78dc-4fbf-8d53-133b279d6fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec8e386b-c97b-47a9-abe5-bf3689ed6aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6045225f-8deb-4aad-8f57-4f6108f9e56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_803</value>
      <webElementGuid>f0abfe3c-33c8-437b-8149-5577f3652d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_803&quot;)</value>
      <webElementGuid>4933e63a-1b8c-4016-9d97-94b40aa3f9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='o_field_input_803']</value>
      <webElementGuid>683bf5be-a337-4027-b426-8a587baf836e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6a419ed9-6be1-421e-8cbe-61ba7a1391c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'name' and @type = 'text' and @id = 'o_field_input_803']</value>
      <webElementGuid>dba0c2df-61a5-42e2-bceb-c516bff8f0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
