<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Responsible Approver</name>
   <tag></tag>
   <elementGuidId>8fc36153-4ea6-4f7d-8071-b5c44df623ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[name=&quot;responsible_approver&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@name='responsible_approver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2018e50b-e1df-4fe9-885e-10e85016756a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_readonly_modifier</value>
      <webElementGuid>88096bcd-837c-4486-bfad-f7d08bf2fce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsible_approver</value>
      <webElementGuid>96fa959d-0918-4b60-a01c-e2313daf45aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Banan Emad Majed AL- Momani</value>
      <webElementGuid>a51e8b76-aac6-4ffc-8993-0abe6b41dfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_form_view o_xxl_form_view o_expense_form o_form_readonly&quot;]/div[@class=&quot;o_form_sheet_bg&quot;]/div[@class=&quot;clearfix position-relative o_form_sheet&quot;]/div[@class=&quot;o_group&quot;]/table[@class=&quot;o_group o_inner_group o_group_col_6&quot;]/tbody[1]/tr[2]/td[2]/span[@class=&quot;o_field_char o_field_widget o_readonly_modifier&quot;]</value>
      <webElementGuid>855e0e28-79d0-4b3b-b0b4-2fe5303c4669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@name='responsible_approver']</value>
      <webElementGuid>2a8e98cb-ffc1-47f9-b5c5-78c90dbb8995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible Approver'])[1]/following::span[1]</value>
      <webElementGuid>40d019e5-3366-407c-962d-96cdb303e877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejection Reason'])[1]/following::span[2]</value>
      <webElementGuid>12bf75de-eb2c-4ed3-b122-698a028eb2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paid By'])[1]/preceding::span[1]</value>
      <webElementGuid>1fcfb25a-a7c2-4f57-8ab7-c78adfeceab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee (to reimburse)'])[1]/preceding::span[1]</value>
      <webElementGuid>03d32a43-f063-4500-9bf2-dad2654b0b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Banan Emad Majed AL- Momani']/parent::*</value>
      <webElementGuid>eebc5be3-40e2-496d-af3c-dfe561c1dfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>646679b9-c156-4a94-9435-8d42b87dea28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'responsible_approver' and (text() = 'Banan Emad Majed AL- Momani' or . = 'Banan Emad Majed AL- Momani')]</value>
      <webElementGuid>a16a1084-ea37-4b2b-8949-b4257e8df659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
