<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reason to reject Expense</name>
   <tag></tag>
   <elementGuidId>712fda10-d5b5-4356-8c4e-9465be5b6f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_857</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>541f83af-2e0f-4523-98c6-064b12776d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_input o_required_modifier</value>
      <webElementGuid>ca547dbf-3f6f-4f5b-9be5-8213cac71063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>eafb5134-7e4d-47a0-8569-1a36458a5589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ecdb03a-10a5-41f4-a34e-c7822353a703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9c9827e0-1272-457e-9688-8cbb9cedc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_857</value>
      <webElementGuid>9911eb3c-2f63-4d79-ae6b-b61f7df049fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_857&quot;)</value>
      <webElementGuid>782b2cfc-ceff-4dd9-8e35-4469468c5f0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_857']</value>
      <webElementGuid>c7b8ddbb-d6bc-443d-bf74-b03c02e6d74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_858']/div/div/main/div/div/div/input</value>
      <webElementGuid>f0f7ab5d-3905-46b7-ae7d-7ea4308d866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/input</value>
      <webElementGuid>0a6c6990-dea5-480b-bd71-0484a91f976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reason' and @type = 'text' and @id = 'o_field_input_857']</value>
      <webElementGuid>6f287ad1-0d8d-4a33-a007-a5cb424685da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
