<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Payment Reference_field</name>
   <tag></tag>
   <elementGuidId>e68f2042-29dc-4b86-95c2-ac75929a636d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[5]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_1367</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91b9fa98-1df7-49ef-ba0c-3eee60f53523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_input</value>
      <webElementGuid>147cf2f6-b9ad-4b10-90ad-1b578ea60f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_reference</value>
      <webElementGuid>6fdb5999-cd5a-4036-a542-cc2096e1fe23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4a48ac2-84b2-407d-8de7-3f9f208315ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f0cb8c3-5ad4-4302-a847-e89baba339a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_1367</value>
      <webElementGuid>871a6ec4-b523-4a95-b00f-3e460feda8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_1367&quot;)</value>
      <webElementGuid>d09b5d58-7c06-4d07-b90c-c796fde9f22d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_1367']</value>
      <webElementGuid>f7b88e7d-7cfe-4f93-b245-effefa3000a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>5ce1d600-4c70-421b-84b2-b72638c5a3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payment_reference' and @type = 'text' and @id = 'o_field_input_1367']</value>
      <webElementGuid>9556165a-9ce1-46be-ae35-1612bcac8b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
