<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_supported version</name>
   <tag></tag>
   <elementGuidId>18f229b0-2410-4d17-a178-0348bf949d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='http_error']/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6c0aecc-5620-408c-b604-d198d7c08ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.odoo.com/documentation/latest/administration/maintain/supported_versions.html</value>
      <webElementGuid>a32f3189-cfcb-4f7d-a492-5d567e44b6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>00452668-fd93-4145-a947-fb137563a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>supported version</value>
      <webElementGuid>e923fd1a-bb83-4120-acf7-5e389cf7cc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;http_error&quot;)/div[@class=&quot;message message-info&quot;]/p[1]/a[1]</value>
      <webElementGuid>7b7e040d-c3d4-45fe-a55e-e178eb414204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='http_error']/div/p/a</value>
      <webElementGuid>3111d647-cb04-4a0f-9ba9-509e2b279fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'supported version')]</value>
      <webElementGuid>be8621ce-cc58-45cb-b8a5-7e6bec71c997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsupported version'])[2]/following::a[1]</value>
      <webElementGuid>c54b9c31-dfa1-49cf-8919-6413db4361e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::a[1]</value>
      <webElementGuid>2fc6b57f-8a0a-4e0e-bed9-ba6a37391ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sunday, 14-Apr-2024 13:19:49 GMT'])[1]/preceding::a[1]</value>
      <webElementGuid>332d1779-7ed8-46b8-b2f9-0752988ffdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='supported version']/parent::*</value>
      <webElementGuid>81ae34b3-7be8-476f-bde5-b03b75b5cfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.odoo.com/documentation/latest/administration/maintain/supported_versions.html')]</value>
      <webElementGuid>b62a7c3b-799f-48c6-bec8-ffcbaa459991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>a2639842-4c76-43c4-b8c1-e138ca44e701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.odoo.com/documentation/latest/administration/maintain/supported_versions.html' and (text() = 'supported version' or . = 'supported version')]</value>
      <webElementGuid>a2520614-b5d6-4c60-bc19-ef481a273151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
