<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Name_field</name>
   <tag></tag>
   <elementGuidId>2beae284-3e1e-4183-bde7-1f3b42a6bab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_1254</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6694eb8-7598-4282-b97e-a277dabe6417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_input o_field_translate o_required_modifier</value>
      <webElementGuid>bfe92123-530f-4973-8e72-8011c874bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>faf0ebf6-a9b8-49f9-ac94-a29c8167e0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Product Name</value>
      <webElementGuid>0d8f845b-319d-4ed5-b0cf-c990a2a7ec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d21128dc-1811-4efd-83c9-9d3fa4e61f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5afeb520-864c-4a8c-98b9-0964e629530c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_1254</value>
      <webElementGuid>5966d943-45b0-4def-a506-22a5c3a18cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_1254&quot;)</value>
      <webElementGuid>ef6aa234-d5a9-4ea2-a00a-adeb7e80e684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_1254']</value>
      <webElementGuid>513b91e0-0b38-47a1-8267-6b70351a063e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>5a6af2a7-7d9e-4a3a-b5c3-eba5fb2046a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Product Name' and @type = 'text' and @id = 'o_field_input_1254']</value>
      <webElementGuid>50a0de78-238e-4ab9-a283-c6939af24737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
