<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loan Amount</name>
   <tag></tag>
   <elementGuidId>0c16a599-b68a-485e-9a34-c86224eb23be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_840</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='o_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06cf3c25-e7d3-48c0-8844-c9b9b4da02d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input</value>
      <webElementGuid>66cac783-964c-441b-ba56-40158c0b794f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfbac64f-d54c-4bb9-98fd-1531a1071c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5359f8a4-c396-45ae-b791-90a066675217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_840</value>
      <webElementGuid>9d9a3292-6e2a-4072-b100-b3c0b666fedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_840&quot;)</value>
      <webElementGuid>2bdb15ac-da49-4683-bfc9-80884c6e069a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_840']</value>
      <webElementGuid>c500c98c-2e21-4817-ab81-fe37587dda57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bc53ade3-3b0b-42b3-b475-e1ea355d5e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'o_field_input_840']</value>
      <webElementGuid>d54d9cbe-2055-4e42-98a0-ae3dff4f2a4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
