<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loan Employee field</name>
   <tag></tag>
   <elementGuidId>08196b90-cbb2-4aa7-9eed-bfdb19618f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_973</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and contains(@class, 'o_input') and contains(@class, 'ui-autocomplete-input') and @autocomplete='off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Employee&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdcaa106-9828-45c2-8c7b-029e1251174c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf802ed6-1f86-4ab3-b6b5-9188dc9b5a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input ui-autocomplete-input</value>
      <webElementGuid>7a3ea0e6-f410-49f9-b321-7d6e30048f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0f10b972-4afc-4947-adb4-5aa2b9627f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_973</value>
      <webElementGuid>4478bcb1-6d63-4791-8b74-dddcaedc0d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_973&quot;)</value>
      <webElementGuid>ba9fb65b-ddca-403e-9744-328da5c1d813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_973']</value>
      <webElementGuid>1fb8de0a-206f-4038-a240-298e791e7dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>6b5a46b0-263d-4f9e-a770-12f56a10a58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'o_field_input_973']</value>
      <webElementGuid>c040b220-df36-4cf0-a7b1-69db805d3d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
