<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time Spent Per Day</name>
   <tag></tag>
   <elementGuidId>9fcee3a4-1b45-4b4e-9bec-1f4ac1581348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_799</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='timespent']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a5ed604-c79e-4a0f-ba9d-4ac759d6611a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_float o_field_number o_field_widget o_input o_required_modifier</value>
      <webElementGuid>5fae0ec6-5acf-4213-9648-f75dc6c2e794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timespent</value>
      <webElementGuid>23f949c6-588e-4a16-a2e0-8efba0abab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>502d351a-25c2-4f7f-8431-73647c7ef33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4289f7b-2820-4275-afb3-8596a4d0089e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_799</value>
      <webElementGuid>6432dd4a-f1a1-464d-813c-3a98e0a639fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_799&quot;)</value>
      <webElementGuid>74cc954f-7d67-446a-aa7f-334c08aa8702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_799']</value>
      <webElementGuid>e181e662-5f1c-4384-89fa-fb284faa3493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_810']/div/div/main/div/div/div/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>5313239d-52aa-498f-a295-2a95ca8fb2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>dbefc544-aee6-4974-b052-8e88ab5a8d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'timespent' and @type = 'text' and @id = 'o_field_input_799']</value>
      <webElementGuid>172c6a2a-8ab2-4452-89ab-e7b9ff9c6dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
