<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ok_Access_Error_button</name>
   <tag></tag>
   <elementGuidId>f9d68e5b-95ab-4776-a58f-ffe14d30a07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal_776 > div.modal-dialog > div.modal-content > footer.modal-footer > button.btn.btn-primary > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[8]/div/div/footer/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf49e15c-6874-4a62-bb89-59b516b69d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>5f5bc30e-57ab-4b5e-a65b-2d0b435dac37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_776&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/footer[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-primary&quot;]/span[1]</value>
      <webElementGuid>54aa278f-552d-4cc9-bb14-42993286312b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_776']/div/div/footer/button/span</value>
      <webElementGuid>949b2568-b64c-427c-900b-248986e5e239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::span[1]</value>
      <webElementGuid>9a93f38d-4bd2-4fb6-945c-a262dfcf101c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Error'])[2]/following::span[1]</value>
      <webElementGuid>fb84bf78-7498-4215-9fc9-457dc3cf4420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/footer/button/span</value>
      <webElementGuid>f3021965-0554-46e7-ae22-57bca2cfe7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>f20a9625-ecbb-4856-9dc9-974daaada94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
