<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remove_filter2</name>
   <tag></tag>
   <elementGuidId>34b421d4-fffb-4e75-9ae9-010e7841740a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2214c60b-6bd0-404b-93b5-5e5e6665cf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b35ab969-becb-4fc3-b0c8-e8a3998c956e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>aa07afe6-19a7-4820-8538-5b9ac102bb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>3a85037b-afef-4909-9a48-e2b99372de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sm fa-remove o_facet_remove</value>
      <webElementGuid>12b2f10c-87a6-4dcb-b599-05a79eb31fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller&quot;]/div[@class=&quot;o_control_panel&quot;]/div[@class=&quot;o_cp_top&quot;]/div[@class=&quot;o_cp_top_right&quot;]/div[@class=&quot;o_cp_searchview&quot;]/div[@class=&quot;o_searchview&quot;]/div[@class=&quot;o_searchview_input_container&quot;]/div[@class=&quot;o_searchview_facet&quot;]/i[@class=&quot;fa fa-sm fa-remove o_facet_remove&quot;]</value>
      <webElementGuid>dcf23d92-616b-45e1-9a3d-29c651fcfeb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>ac0a52ed-9f5e-4a04-90a5-f74ddab1144e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Remove']</value>
      <webElementGuid>4e8fcf88-e979-4fea-b755-a8d26c1b4510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
