<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No. of Hours field</name>
   <tag></tag>
   <elementGuidId>60c11907-9099-4aad-8543-e8deb6720a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_823</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed7235ba-254b-4aa2-84bd-e54d6eb61927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_float o_field_number o_field_widget o_input o_required_modifier</value>
      <webElementGuid>19ea9065-c372-480c-9db7-e037ea892df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>x_noofhours</value>
      <webElementGuid>55be16b6-d9e8-4aa8-8be3-2fa09ffe06c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89c232c6-924b-4d4f-8919-59a271df1b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84d4e1b1-b5ce-4155-9cf1-efe593a025cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_823</value>
      <webElementGuid>90c084f5-d57a-4f21-941b-afbc3a4633c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_823&quot;)</value>
      <webElementGuid>bc3bb8a3-6f77-4c15-8e93-cb250690e589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_823']</value>
      <webElementGuid>089a0797-70a6-46a2-9211-283149142625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_824']/div/div/main/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>1744382c-ec78-46f3-8036-04b177732326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>8656f64b-b572-4d5a-b249-17790b53fd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'x_noofhours' and @type = 'text' and @id = 'o_field_input_823']</value>
      <webElementGuid>c95065df-cb1f-4fd7-962a-ffac6b6e6b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
