<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Origin</name>
   <tag></tag>
   <elementGuidId>e75925a4-4535-4b2d-bf33-8ee1dd780962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[contains(@class,'o_input o_field_widget')])[2]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_858</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9303f07-289a-47dc-8e0d-9f8a248b9d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input o_field_widget o_required_modifier</value>
      <webElementGuid>84f616f2-e1aa-4cb2-a581-ceff1b6d91e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>x_studio_destination</value>
      <webElementGuid>bfd9a436-051f-45a9-a2d2-f5ec104fc85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_858</value>
      <webElementGuid>70dfaed7-2246-46d0-9125-e5b7aaf16030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JordanEgyptIraqKuwaitOmanSaudi ArabiaSpainUAEUSA</value>
      <webElementGuid>2dcc08f9-c7ad-46b5-952b-9a56a5c5bdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_858&quot;)</value>
      <webElementGuid>f2bb54a9-544f-4205-90f9-e6479089c004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='o_field_input_858']</value>
      <webElementGuid>b9a60198-610c-4254-add6-2e6ee1adff07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/following::select[1]</value>
      <webElementGuid>9c0512b1-1242-4d36-bc82-bab778c89aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origin'])[1]/following::select[2]</value>
      <webElementGuid>f405f4f3-cc00-497a-9556-b2b0f2972940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::select[1]</value>
      <webElementGuid>0b184cde-efda-419f-8828-d4a887ec798e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::select[1]</value>
      <webElementGuid>3e8b8cf0-9567-41af-9863-1a585d971f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>3de83941-41ad-4c75-b3fb-3b9a2d2f6c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'x_studio_destination' and @id = 'o_field_input_858' and (text() = 'JordanEgyptIraqKuwaitOmanSaudi ArabiaSpainUAEUSA' or . = 'JordanEgyptIraqKuwaitOmanSaudi ArabiaSpainUAEUSA')]</value>
      <webElementGuid>f0c50c1d-f39c-4afd-be04-05e952eadc56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
