<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survey Title_field</name>
   <tag></tag>
   <elementGuidId>d9647481-cc2d-445a-b59a-d19a52573c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_1749</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62943cf5-2407-49a5-b7ec-93c56d20587a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_input o_field_translate o_required_modifier</value>
      <webElementGuid>6835ed07-b8e2-48a6-8248-63882e3aaa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>a9b1375e-cf43-4384-bb50-a5029ce3d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Satisfaction Survey</value>
      <webElementGuid>513b5aff-84dc-4853-ad77-873d0c38f5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48e64b5f-8fa2-41a9-ba46-84749560d2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4680701-0048-49b8-b990-407018ab9e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_1749</value>
      <webElementGuid>d255a472-9a94-4740-890a-1c0bbe40066b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_1749&quot;)</value>
      <webElementGuid>122116e9-85d2-4bc2-a6e2-6a076e9cab9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_1749']</value>
      <webElementGuid>e8b87a68-a4be-4f7b-8bbe-6937bbc2ff5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>492447e6-4cca-47d5-a181-9dbcd4f745f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'title' and @placeholder = 'e.g. Satisfaction Survey' and @type = 'text' and @id = 'o_field_input_1749']</value>
      <webElementGuid>2ad6210d-77f3-42ec-b6de-8c6cfa89551d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
