<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Appraisal</name>
   <tag></tag>
   <elementGuidId>3ac4ff6c-f949-4b41-b978-9d9bef85910d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_13']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_13 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee5920bd-628a-4d4a-a098-395cb7acfc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>4a6d77dd-bb6e-489b-add7-19c4982bc81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_13&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>7dcc6fd1-ff16-41a4-a002-579231283614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_13']/div</value>
      <webElementGuid>7c983be0-c7b7-47cf-8411-dc5e55b03d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[14]/div</value>
      <webElementGuid>dbbd9c89-ba3b-424f-aae7-edb0b154b6a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
