<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apps</name>
   <tag></tag>
   <elementGuidId>e3493da4-b8a5-4c4a-ba02-f88c9805404a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_26']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_26 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe47bb08-1e28-4f86-834c-31962944cbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>5924c938-d10b-4a0c-a638-c348f2912adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_26&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>71afb0ee-ca82-474f-9c85-5752a2757355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_26']/div</value>
      <webElementGuid>e01a8178-5767-486a-a7dc-f91d91f8fbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[27]/div</value>
      <webElementGuid>55d14c10-22f0-4c2a-a8d7-c4ad78b091f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
