<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendances</name>
   <tag></tag>
   <elementGuidId>823fa9bd-da99-476d-ab13-6f49e09da539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_22']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_22 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>663ff215-50ea-4299-93c8-1ee6283b22e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>aa28a80c-b492-467d-9319-a46b29378532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_22&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>31f3333a-22b6-4dec-8f23-4e0cba38fc0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_22']/div</value>
      <webElementGuid>8dce3737-5042-4575-a648-99d734f65385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[23]/div</value>
      <webElementGuid>1a15ee2c-f5e8-4a49-a4cc-75715c980b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
