<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar</name>
   <tag></tag>
   <elementGuidId>b485a044-b44b-4126-941e-85e6c7518013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_3']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_3 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b362fba-61e4-446a-9a81-86c36d1c5795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>8329ba30-e11b-4b68-99e1-69a2bfe914fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_3&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>ba5466cf-82f4-4719-bff0-0f554cbe8862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_3']/div</value>
      <webElementGuid>32a9b371-a748-4aab-a95c-c99da4ab29f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div</value>
      <webElementGuid>9dc03f22-cd39-4a47-a6f4-8a9ef74f1196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
