<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CRM</name>
   <tag></tag>
   <elementGuidId>f192be57-f99b-4d59-ab86-657061757bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_5']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_5 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5aad981d-6bef-4fb2-a0be-bd7e4394ea66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>3c7f1448-aa0a-4755-817a-199b5c703801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_5&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>06fcfb52-d93b-40f7-94d0-41d2e4c9d956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_5']/div</value>
      <webElementGuid>2e6d74a1-8dc7-4435-a759-307744f4645b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/div</value>
      <webElementGuid>7cfa22d1-b910-4047-990b-342e561552de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
