<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Discuss</name>
   <tag></tag>
   <elementGuidId>bd0db299-7a5e-4e1c-8748-3baf8309c4db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_2']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_2 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8275490c-08eb-4abe-bf3c-5bf236fbb607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>860a62a1-aeab-4b55-9a4b-5df0cf993e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_2&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>bf528884-d9bf-44d6-b5d3-008a5f025878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_2']/div</value>
      <webElementGuid>c21a03fb-0533-4050-889b-9e936c6b2e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div</value>
      <webElementGuid>aff55dbd-28fc-4f48-a696-18ccb5909639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
