<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employees</name>
   <tag></tag>
   <elementGuidId>98be7efb-6f20-434d-b8ce-887d0d734d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_19']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_19 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6947dc46-847f-49b2-9371-0102abd14295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>a1483af0-e997-423f-beef-a20fb46ee800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_19&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>bdc16953-5443-41f6-b7db-a6ed2d951e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_19']/div</value>
      <webElementGuid>cf18d8ca-97ef-478a-9f57-ecd8534a2367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[20]/div</value>
      <webElementGuid>fad585a9-483d-4546-a531-43a918bebf56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
