<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loans</name>
   <tag></tag>
   <elementGuidId>65334f7a-ff7a-4b67-98ba-a4c29a7f22b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result_app_1 > div.o_app_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[.//div[@class='o_caption' and text()='Loans']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21f6a375-13b6-4919-b0e8-a214dea5fa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>2ffe5b11-855b-4df9-bef8-01207959e129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_1&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>2c9c3c52-4f74-48ba-963c-a7308463953d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_1']/div</value>
      <webElementGuid>c2a5b1b4-6b70-4c62-9caa-d20c61322c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div</value>
      <webElementGuid>557bd57e-b7cb-4f3b-b3d2-056f3d2d08c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
