<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Maintenance</name>
   <tag></tag>
   <elementGuidId>948941f0-4a5d-4855-92c3-e27a64102e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_25']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_25 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7421390a-6094-432b-a77c-d56688935ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>7eb9c123-1e4c-4ea2-ae31-a087b29a3f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_25&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>aeeb994a-a695-4085-a5dd-d3d811427b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_25']/div</value>
      <webElementGuid>ae51208c-3c1e-4771-ae2a-96e4f529b32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[26]/div</value>
      <webElementGuid>7faa0dab-c64e-4356-a4b6-f60f754c98bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
