<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Payroll</name>
   <tag></tag>
   <elementGuidId>42fb4647-a863-41fb-93d1-38c28e6d1711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_15']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_15 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb4dfafd-adb6-40ff-b4ea-7ca51d948f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>7db0466c-80cf-47b5-a2c3-491c8130e920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_15&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>87b84703-21a6-4c89-b627-0feb79e181cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_15']/div</value>
      <webElementGuid>f4716311-75f8-4db9-a658-85a2f78d1145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[16]/div</value>
      <webElementGuid>0f2d2acf-a853-4a81-b3fe-1d4371554485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
