<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purchase</name>
   <tag></tag>
   <elementGuidId>d6284dd2-dd90-46b8-a5f4-a416cf68ed07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_11']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_11 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccdad27b-3512-4847-b071-3752d0db43c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>75db2118-f218-4ee8-a879-f51463d28b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_11&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>f4db1135-f854-4c96-81e0-8276d62dbeda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_11']/div</value>
      <webElementGuid>3dd829e7-4f09-4065-ba32-b1c567a0a4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[12]/div</value>
      <webElementGuid>34546f17-6a56-4927-9816-9687d1ae4396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
