<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subscriptions</name>
   <tag></tag>
   <elementGuidId>b05e7c32-b7c1-42ec-b214-a1dbd47fcf94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_7']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result_app_7 > div.o_app_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed03390f-ddb2-4b74-b5e4-2457f1264290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>489b0681-1c23-4a50-8e01-589a3a066c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_7&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>782822b1-e303-451f-9c16-787a4d90c72e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_7']/div</value>
      <webElementGuid>9cd8c8d7-8374-4f7e-a1b4-81a2fd906967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]/div</value>
      <webElementGuid>ab817433-c8c3-4dc4-a679-3dbaace54a71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
