<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time Off</name>
   <tag></tag>
   <elementGuidId>d0abf770-8806-4229-8d57-563bee1b11a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result_app_23 > div.o_app_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Time Off' or . = 'Time Off')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>992bbf2b-58ba-4581-a139-3a0f99a1222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>c4cbfeea-fb4b-451a-987c-4894e88238fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_23&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>28e10762-958b-4bd8-b032-a4722ed53fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_23']/div</value>
      <webElementGuid>631ecc52-8596-436a-abc4-0099bb64df52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[24]/div</value>
      <webElementGuid>23fe2e27-3133-4587-bdfe-b540f617860b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
