<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Timesheets</name>
   <tag></tag>
   <elementGuidId>2a1dcaf2-24b1-497a-b7c1-12980afe790b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result_app_17 > div.o_app_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Timesheets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3531585b-02d0-4ab5-8890-aa21b2889b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_app_icon</value>
      <webElementGuid>ee0145e6-2a1c-44b5-b611-361981bd85fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_17&quot;)/div[@class=&quot;o_app_icon&quot;]</value>
      <webElementGuid>99dad597-59b5-4c48-9b5e-8db97b540f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_17']/div</value>
      <webElementGuid>00042315-e76c-4629-9a34-58ee941a52c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[18]/div</value>
      <webElementGuid>c0c9fe10-2c5b-4c70-ba53-336ab7967475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
