<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website</name>
   <tag></tag>
   <elementGuidId>42915135-a496-4bc3-a163-e0e9814889db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_8']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc4813ba-104a-481c-a060-6d1cefa3e00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plane</value>
      <webElementGuid>7c6be580-f27c-4352-8550-171d9d4c00aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_8&quot;)/div[@class=&quot;o_app_icon&quot;]/i[@class=&quot;fa fa-plane&quot;]</value>
      <webElementGuid>b79a2e56-099c-4a66-acbc-c887324e405f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_8']/div/i</value>
      <webElementGuid>95450836-92df-4fae-801c-b589fe0c386f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/div/i</value>
      <webElementGuid>3c010eec-223a-40b8-b919-ab205ff950bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
