<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vendor__Name_field</name>
   <tag></tag>
   <elementGuidId>f0835f30-8b14-49ee-8935-21efd605363b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_933</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a79d1a3-34be-439a-acf9-f9c254230739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_field_char o_field_widget o_input o_required_modifier oe_edit_only</value>
      <webElementGuid>4f5259d3-31a0-4715-93bf-1c7059d69a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f425917a-e099-41fe-89ef-1dabc97b74ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>97298aa3-4d52-4904-842d-8ed75ba2b8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6aae5e80-25c4-408d-b392-0248360305a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3df9f050-3c37-49ea-bd58-1c1137aed794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_933</value>
      <webElementGuid>034097e8-5596-4ece-81e0-fb6d4ff92de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_933&quot;)</value>
      <webElementGuid>a47bfdd7-3e01-40e4-861b-926a4ae6ca43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_933']</value>
      <webElementGuid>cd18e59e-2875-40a1-9f01-5e9110f670fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/div/input</value>
      <webElementGuid>826b0d92-c234-45de-8ce7-010dc59260ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Name' and @type = 'text' and @id = 'o_field_input_933']</value>
      <webElementGuid>505f66f9-5d9f-4887-8175-81cb5b6c0e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
