<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Department_field</name>
   <tag></tag>
   <elementGuidId>a35b125b-c489-42f9-82f3-0a2224bf8556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr/td[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o_field_input_873</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27abed91-6e4b-4147-8546-dfa36b3825dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11e62879-ffad-4001-bf17-d7348e851698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input ui-autocomplete-input</value>
      <webElementGuid>0320f817-2ddb-4ed4-9bda-d7c47822ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd998d15-a7cb-4023-ac78-65ad24fbb90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o_field_input_873</value>
      <webElementGuid>6f42ebd2-4988-4b20-8f85-d623f7533f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o_field_input_873&quot;)</value>
      <webElementGuid>d99b87a8-6623-4b57-8da0-41744b30c9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o_field_input_873']</value>
      <webElementGuid>e02d984f-0995-4709-8186-3ed9251b59ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/div/div/input</value>
      <webElementGuid>9620d12d-3926-4a2a-abe8-6568a60c9745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'o_field_input_873']</value>
      <webElementGuid>6863677d-a4f0-4ca7-ad0e-f4224b795406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
